name: CI
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: build package
        run: |
          make install
        env:
          CI: true
      - name: Run linter
        run: |
          make lint
      - name: Test & publish code coverage
          uses: paambaati/codeclimate-action@v3.0.0
          env:
            CC_TEST_REPORTER_ID: cd6d06ee485b8e2744d5e9277e266a338eb6884458809194f75c1f7751d202bd
          with:
            coverageCommand: make test-coverage
            debug: true